# Meta Data for SEO

## Homepage
title = "Davinici Sheet"
titleSeparator = "|"
titleAddition = "Unlock the Power of Data with Davinici Sheet AI Solutions."
description = "Unlock the potential of your data with Davinici Sheet's AI-powered solutions. Experience personalized content and effortless analysis for quick and easy results."

## Documentation
# docsVersion = "0.3"

## Open Graph
images = ["logo-doks.png"]
ogLocale = "en_US"
domainTLD = "hodgeluke.com"
titleHome = "Davinici Sheet"

## Twitter Cards
twitterSite = "@HodgeLukee"
twitterCreator = "@IamNarahariDasa"

## JSON-LD
# schemaType = "Person"
schemaType = "Organization"
schemaName = "Davinici Sheet"
schemaAuthor = "Narahari Luke"
schemaAuthorTwitter = "https://twitter.com/IamNarahariDasa"
schemaAuthorLinkedIn = "https://www.linkedin.com/in/narahari-dasa/"
schemaAuthorGitHub = "https://github.com/MrLuke2"
schemaLocale = "en-US"
schemaLogo = "logo-doks.png"
schemaLogoWidth = 512
schemaLogoHeight = 512
schemaImage = "logo-doks.png"
schemaImageWidth = 1280
schemaImageHeight = 640
schemaTwitter = "https://twitter.com/HodgeLukee"
schemaLinkedIn = "https://www.linkedin.com/in/narahari-dasa/"
schemaGitHub = "https://github.com/DSamuelHodge"
schemaSection = "blog"

## Sitelinks Search Box
siteLinksSearchBox = false

## Chrome Browser
themeColor = "#fff"

# Images
quality = 85
bgColor = "#fff"
landscapePhotoWidths = [900, 800, 700, 600, 500]
portraitPhotoWidths = [800, 700, 600, 500]
lqipWidth = "20x"
smallLimit = "300"

# Images
imageResponsive = true
imageConvertTo = "webp"
imageImageSizes = ["480", "720", "1080", "1280", "1600", "2048"]
singleSize = false
imageAddClass = "img-fluid lazyload blur-up"

### Image template
defaultImage = "./assets/images/" # put in `./assets/images/`
fillImage = "1270x740 Center"     # normalize image size

# Footer
footer = "Powered by <a class=\"text-muted\" href=\"https://www.hodgeluke.com/\"><b>Hodge & Luke</b></a> | <a class=\"text-muted\" href=\"https://gohugo.io/\">Hugo</a> | <a class=\"text-muted\" href=\"https://getdoks.org/\"><b>Davinici Sheet</b></a>"


# Feed
copyRight = "Copyright (c) 2022-2023 Narahari Luke"

# Alert
alert = true
alertDismissable = true
# alertText = "Introducing the Doks child theme, several DX + UX updates, and more! <a class=\"alert-link stretched-link\" href=\"https://getdoks.org/blog/doks-v0.2/\" target=\"_blank\" rel=\"noopener\">Check out Doks v0.2</a>"
alertText = "Introducing Davinici Sheet, User-friendly Ai Automation in your Sheets, and more! <a class=\"alert-link stretched-link\" href=\"https://www.hodgeluke.com/\">Check Out Davinici Sheet v0.1</a>"

# Edit Page
# repoHost [Github | Gitea | GitLab | Bitbucket | BitbucketServer ] is used for building the edit link based on git hoster
repoHost = "GitHub"
#repoHost = "Gitea"
docsRepo = "https://github.com/h-enk/doks"
docsRepoBranch = "master"
docsRepoSubPath = ""
editPage = false
lastMod = false

[sections]
sectionNav = ["docs", "guides"]

[options]
lazySizes = true
clipBoard = true
instantPage = true
flexSearch = true
searchSectionsShow = []
searchSectionsIndex = []
darkMode = true
bootStrapJs = true
breadCrumb = true
highLight = true
kaTex = false
multilingualMode = false
docsVersioning = false
fullWidth = false
navbarSticky = true
toTopButton = false
scrollSpy = false        # experimental; needs Bootstrap >= 5.2.0-beta1

[menu]
[menu.section]
auto = true
collapsibleSidebar = true
