name = "Davinici Sheet"
license = "MIT"
licenselink = "https://github.com/h-enk/doks/blob/master/LICENSE"
description = "Davinici Sheets empowers data w/ AI. From personalized content to automated analysis, it provides everything needed to unlock data's potential. Get results quickly & easily."

homepage = ""
demosite = ""

tags = [
  "landing page",
  "documentation",
  "blog",
  "minimal",
  "modern",
  "customizable",
  "search",
  "dark mode",
  "bootstrap",
]
features = [
  "security aware",
  "fast by default",
  "seo-ready",
  "development tools",
  "bootstrap framework",
  "netlify-ready",
  "full text search",
  "page layouts",
  "dark mode",
]

[author]
name = "Narahari Luke"
homepage = "https://hodgeluke.com"
